apiVersion: v1
kind: Service
metadata:
  name: sale-service
spec:
  type: NodePort
  selector:
    app: sale-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # porta externa (opcional, se quiser fixar)