apiVersion: v1
kind: Service
metadata:
  name: sale-service
spec:
  type: NodePort
  selector:
    app: sale-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082  # porta externa (opcional, se quiser fixar)