apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sale
  labels:
    app: postgres-sale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sale
  template:
    metadata:
      labels:
        app: postgres-sale
    spec:
      containers:
        - name: postgres-sale
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: salesdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
