name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Dar permissão para o gradlew
      run: chmod +x gradlew

    - name: Build e Testes
      run: ./gradlew build

    - name: Build da imagem Docker
      run: |
        docker build -t sale-service:${{ github.sha }} .
        docker tag sale-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/sale-service:latest

    - name: Login no DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push da imagem
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/sale-service:latest
